export {default as Navbar } from './Navbar'
export {default as FAQ } from './FAQ'
export {default as Features } from './Features'
export {default as Footer } from './Footer'
export {default as Header } from './Header'
export {default as Sponsors } from './Sponsors'
export {default as Team } from './Team'
export {default as WhyChooseUs } from './WhyChooseUs'